# Generated by Django 3.1.2 on 2020-10-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phonenumber',
            new_name='phone',
        ),
    ]
